apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-cloud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-cloud
  template:
    metadata:
      labels:
        app: mini-cloud
    spec:
      containers:
      - name: mini-cloud
        image: myminiacr.azurecr.io/mini-cloud-service:latest
        ports:
        - containerPort: 5000

